[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "pandas-ta>=0.3.14b0",
    "streamlit>=1.42.0",
    "yfinance>=0.2.52",
    "python-telegram-bot>=20.0",
]
